name: test

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test
        run: |
          make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
